### ISSUE TITLE
Connection closed by the server

### ISSUE THREAD

**Issue by Kreonid** [Ro0tz5/telethon-faketls#3]

**Comment by hntcAir** [comment]
same problem

**Comment by hntcAir** [comment]
raise exceptions.IncompleteReadError(incomplete, n)
asyncio.exceptions.IncompleteReadError: 0 bytes read on a total of 1 expected bytes
WARNING:telethon.network.connection.connection:Server closed the connection: 0 bytes read on a total of 1 expected bytes
ERROR:telethon.network.mtprotosender:Unhandled error while receiving data

**Comment by hntcAir** [comment]
File "C:\Users\hntc\AppData\Roaming\Python\Python311\site-packages\telethon\network\connection\tcpmtproxy.py", line 76, in readexactly
    return self._decrypt.encrypt(await self._reader.readexactly(n))
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hntc\AppData\Roaming\Python\Python311\site-packages\TelethonFakeTLS\FakeTLS\TLSInOut.py", line 85, in readexactly
    tls_data = await self.read(1, ignore_buf=True)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hntc\AppData\Roaming\Python\Python311\site-packages\TelethonFakeTLS\FakeTLS\TLSInOut.py", line 62, in read
    tls_rec_type = await self.upstream.readexactly(1)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\asyncio\streams.py", line 726, in readexactly
    raise exceptions.IncompleteReadError(incomplete, n)
asyncio.exceptions.IncompleteReadError: 0 bytes read on a total of 1 expected bytes
WARNING:telethon.network.connection.connection:Server closed the connection: 0 bytes read on a total of 1 expected bytes
ERROR:telethon.network.mtprotosender:Unhandled error while receiving data
Traceback (most recent call last):
  File "C:\Users\hntc\AppData\Roaming\Python\Python311\site-packages\telethon\network\mtprotosender.py", line 505, in _recv_loop
